// Template data with SVG-based gradient backgrounds
export const CATEGORIES = [
  { id: 'all', label: 'All', emoji: '✨' },
  { id: 'birthday', label: 'Birthday', emoji: '🎂' },
  { id: 'anniversary', label: 'Anniversary', emoji: '💕' },
  { id: 'festival', label: 'Festivals', emoji: '🎉' },
  { id: 'congratulations', label: 'Congrats', emoji: '🏆' },
  { id: 'thankyou', label: 'Thank You', emoji: '🙏' },
  { id: 'love', label: 'Love', emoji: '❤️' },
];

export const TEMPLATES = [
  // BIRTHDAY
  {
    id: 'b1',
    category: 'birthday',
    title: 'Golden Celebration',
    isPremium: false,
    gradient: 'linear-gradient(135deg, #1a0533 0%, #4a1080 40%, #ff6b35 100%)',
    accentColor: '#f5c842',
    pattern: 'confetti',
    message: 'Wishing you a day filled with joy!',
    emoji: '🎂',
    textPosition: 'bottom',
  },
  {
    id: 'b2',
    category: 'birthday',
    title: 'Midnight Party',
    isPremium: false,
    gradient: 'linear-gradient(135deg, #0d0d2b 0%, #1a1a4e 50%, #2d0052 100%)',
    accentColor: '#b57bee',
    pattern: 'stars',
    message: 'Another year of amazing adventures!',
    emoji: '🎉',
    textPosition: 'center',
  },
  {
    id: 'b3',
    category: 'birthday',
    title: 'Tropical Bash',
    isPremium: true,
    gradient: 'linear-gradient(135deg, #004040 0%, #006644 50%, #ff4444 100%)',
    accentColor: '#00d4aa',
    pattern: 'tropical',
    message: 'Happy Birthday, superstar! 🌺',
    emoji: '🌺',
    textPosition: 'top',
  },
  {
    id: 'b4',
    category: 'birthday',
    title: 'Rose Gold Dream',
    isPremium: true,
    gradient: 'linear-gradient(135deg, #3d1030 0%, #8b3060 50%, #d4a0b0 100%)',
    accentColor: '#f5c842',
    pattern: 'floral',
    message: 'You make every day brighter ✨',
    emoji: '🌸',
    textPosition: 'bottom',
  },
  // ANNIVERSARY
  {
    id: 'a1',
    category: 'anniversary',
    title: 'Eternal Bond',
    isPremium: false,
    gradient: 'linear-gradient(135deg, #1a0020 0%, #4d0040 50%, #800060 100%)',
    accentColor: '#ff6b9d',
    pattern: 'hearts',
    message: 'Celebrating our beautiful journey together ❤️',
    emoji: '💕',
    textPosition: 'center',
  },
  {
    id: 'a2',
    category: 'anniversary',
    title: 'Golden Years',
    isPremium: true,
    gradient: 'linear-gradient(135deg, #1a1200 0%, #4d3800 50%, #8b6914 100%)',
    accentColor: '#f5c842',
    pattern: 'geometric',
    message: 'Every moment with you is precious 💍',
    emoji: '💍',
    textPosition: 'bottom',
  },
  {
    id: 'a3',
    category: 'anniversary',
    title: 'Moonlit Romance',
    isPremium: false,
    gradient: 'linear-gradient(135deg, #050520 0%, #10103a 50%, #200060 100%)',
    accentColor: '#c8b4ff',
    pattern: 'moon',
    message: 'To infinity and beyond, together 🌙',
    emoji: '🌙',
    textPosition: 'top',
  },
  // FESTIVAL
  {
    id: 'f1',
    category: 'festival',
    title: 'Diwali Glow',
    isPremium: false,
    gradient: 'linear-gradient(135deg, #1a0a00 0%, #4d2500 50%, #ff7700 100%)',
    accentColor: '#f5c842',
    pattern: 'diya',
    message: 'May your life be filled with light! 🪔',
    emoji: '🪔',
    textPosition: 'center',
  },
  {
    id: 'f2',
    category: 'festival',
    title: 'Christmas Magic',
    isPremium: false,
    gradient: 'linear-gradient(135deg, #001a00 0%, #003300 50%, #004400 100%)',
    accentColor: '#ff4444',
    pattern: 'snowflakes',
    message: 'Wishing you joy and peace! 🎄',
    emoji: '🎄',
    textPosition: 'bottom',
  },
  {
    id: 'f3',
    category: 'festival',
    title: 'Eid Mubarak',
    isPremium: true,
    gradient: 'linear-gradient(135deg, #001a10 0%, #004030 50%, #006644 100%)',
    accentColor: '#f5c842',
    pattern: 'crescent',
    message: 'Eid Mubarak! May Allah bless you ☪️',
    emoji: '☪️',
    textPosition: 'center',
  },
  {
    id: 'f4',
    category: 'festival',
    title: 'Holi Splash',
    isPremium: true,
    gradient: 'linear-gradient(135deg, #1a0040 0%, #600020 50%, #002040 100%)',
    accentColor: '#ff6bef',
    pattern: 'colorful',
    message: 'Happy Holi! Play with colors! 🌈',
    emoji: '🌈',
    textPosition: 'top',
  },
  // CONGRATULATIONS
  {
    id: 'c1',
    category: 'congratulations',
    title: 'Victory Lap',
    isPremium: false,
    gradient: 'linear-gradient(135deg, #001020 0%, #002040 50%, #003060 100%)',
    accentColor: '#f5c842',
    pattern: 'stars',
    message: 'You did it! So incredibly proud of you 🏆',
    emoji: '🏆',
    textPosition: 'center',
  },
  {
    id: 'c2',
    category: 'congratulations',
    title: 'Sky\'s the Limit',
    isPremium: true,
    gradient: 'linear-gradient(135deg, #050030 0%, #200060 50%, #400090 100%)',
    accentColor: '#00d4aa',
    pattern: 'rockets',
    message: 'Soaring to new heights! 🚀',
    emoji: '🚀',
    textPosition: 'bottom',
  },
  // THANK YOU
  {
    id: 't1',
    category: 'thankyou',
    title: 'Gratitude Garden',
    isPremium: false,
    gradient: 'linear-gradient(135deg, #001510 0%, #003020 50%, #005030 100%)',
    accentColor: '#00d4aa',
    pattern: 'floral',
    message: 'Thank you from the bottom of my heart 🌻',
    emoji: '🌻',
    textPosition: 'center',
  },
  {
    id: 't2',
    category: 'thankyou',
    title: 'Warm Embrace',
    isPremium: true,
    gradient: 'linear-gradient(135deg, #200010 0%, #400020 50%, #600030 100%)',
    accentColor: '#ff6b9d',
    pattern: 'hearts',
    message: 'Words can\'t express how thankful I am 💝',
    emoji: '💝',
    textPosition: 'bottom',
  },
  // LOVE
  {
    id: 'l1',
    category: 'love',
    title: 'Heartbeat',
    isPremium: false,
    gradient: 'linear-gradient(135deg, #1a0010 0%, #4d0030 50%, #800050 100%)',
    accentColor: '#ff6b9d',
    pattern: 'hearts',
    message: 'You are my everything ❤️',
    emoji: '❤️',
    textPosition: 'center',
  },
  {
    id: 'l2',
    category: 'love',
    title: 'Stardust',
    isPremium: true,
    gradient: 'linear-gradient(135deg, #050020 0%, #1a0050 50%, #300080 100%)',
    accentColor: '#ff99cc',
    pattern: 'stars',
    message: 'In a universe full of stars, you\'re my favorite ✨',
    emoji: '💫',
    textPosition: 'bottom',
  },
];
